networks:
  rede_php:
    driver: bridge

services:
  php:
    build:
      context: .
    user: "www-data"  # Executa o contêiner como o usuário www-data
    container_name: php
    restart: always
    volumes:
      - ./:/var/www/html/
    networks:
      - rede_php
    ports:
      - "80:80"

  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Usando variável do .env
      MYSQL_TIME_ZONE: ${MYSQL_TIME_ZONE}  # Usando variável do .env
    volumes:
      - ./acesso_e_logs.sql:/docker-entrypoint-initdb.d/1.sql
      # - ./set_timezone.sql:/docker-entrypoint-initdb.d/2_set_timezone.sql
    networks:
      - rede_php
    ports:
      - "3306:3306"
    command: --default-time-zone='${MYSQL_TIME_ZONE}'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    networks:
      - rede_php
    ports:
      - "8080:80"